spring.application.name=agenticcommerce
razorpay.key.id=rzp_test_TS47C6d5Dc8yz4
razorpay.key.secret=qm50GOyyrKGn9BeeJzEMRvy0


spring.datasource.url=jdbc:mysql://localhost:3306/agentic_commerce
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
